Feature/coingecko usage route
aialphanovatide/ai-alpha-backend pull request #109
Opened 2024-09-24 18:51 UTC by agusbusta

CoinGecko API Usage Endpoint Migration

This PR moves the CoinGecko API usage endpoint from the news bots server to the AI Alpha server. The new implementation includes:

- A new GET endpoint at /api/v1/coingecko/usage
- Improved error handling with detailed error messages
- A standardized response format using the create_response function
- Secure API key storage using environment variables
- Additional logging for easier debugging of API key issues
- Updated documentation for the new endpoint

2024-09-27 15:50 UTC, daviddflix requested changes
## Feedback

I've checked the PR and everything seems to be fine, please adjust the details about the name of the endpoint and make sure you have the latest changes of the Develop branch.

2024-09-27 15:50 UTC, daviddflix commented on routes/coingecko/coingecko_usage.py
> +@coingecko_bp.route('/api/v1/coingecko/usage', methods=['GET'])
@agusbusta let's update the name of the endpoint to "coingecko/usage"

2024-09-27 16:54 UTC, agusbusta commented
Name fixed!

2024-09-30 14:02 UTC, daviddflix approved these changes

2024-09-30 14:02 UTC, merged