Fix: CHART date fix, add functions to make correct request to CG API
aialphanovatide/ai-alpha-backend pull request #88
Opened 2024-09-06 18:31 UTC by agusbusta

OHLC Data Consolidation and Interval Handling
This update addresses the issue of inconsistent data intervals in OHLC (Open, High, Low, Close) responses. Previously, the API was returning data in 4-hour intervals regardless of the requested interval. The fix implements a data consolidation function to ensure that the returned data matches the requested interval (daily, weekly, etc.).
Key Changes:
Implemented a new consolidate_ohlc_data function:
Processes raw OHLC data and consolidates it based on the specified interval.
Supports daily ('1d') and weekly ('1w') intervals, with extensibility for other intervals.
Ensures that each data point represents the correct time period with accurate OHLC values.
Modified the get_ohlc_coingecko_data function:
Now applies the consolidate_ohlc_data function to the raw API response.
Ensures that the data is properly consolidated before being returned to the client.
Updated data processing flow:
Raw data is fetched from the CoinGecko API.
Data is then consolidated based on the requested interval.
Consolidated data is processed to convert timestamps to ISO format.

2024-09-17 13:20 UTC, daviddflix requested changes
## Feedback

- Please make sure all endpoints work, and remove any code that we don't use anymore.

2024-09-17 13:20 UTC, daviddflix commented on routes/chart/chart_olhc.py
> +headers = {'X-Cg-Pro-Api-Key': "CG-xXCJJaHa7QmvQNWyNheKmSfG"}
- This must not happen again, the API key is there, please remove it.

2024-09-17 13:20 UTC, daviddflix commented on routes/chart/chart_olhc.py
>  # List of cryptocurrencies we have available
- Use the database to get all available coins.

2024-09-17 13:20 UTC, daviddflix commented on routes/chart/chart_olhc.py
>  import logging
- Remove the logger, as this is just for debugging.

2024-09-17 18:39 UTC, agusbusta commented
Removed api key form code, now located in env file

2024-09-19 20:08 UTC, agusbusta commented
hey @daviddflix its ready to review!

2024-09-20 22:27 UTC, daviddflix approved these changes

2024-09-20 22:27 UTC, merged